spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=1

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    instance:
        instance-id: ${spring.application.name}:${random.value}

server:
  port: 8089
